#ifndef PLUGINCLIPEFFECTS_GLOBAL_H
#define PLUGINCLIPEFFECTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINCLIPEFFECTS_LIBRARY)
#  define PLUGINCLIPEFFECTS_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINCLIPEFFECTS_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINCLIPEFFECTS_GLOBAL_H
